name: multi_media_picker_example
description: Demonstrates how to use the multi_media_picker plugin.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  multi_media_picker:
    path: ../
  path: ^1.9.0
  path_provider: ^2.1.5
  world_countries: ^3.0.0

dev_dependencies:
  dart_code_metrics_presets: ^2.20.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  disable-swift-package-manager: false
  uses-material-design: true

  assets:
    - assets/
