name: multi_media_picker_example
description: "Demonstrates how to use the multi_media_picker plugin."
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  multi_media_picker:
    path: ../
  world_countries: ^2.0.2

dev_dependencies:
  dart_code_metrics_presets: ^2.19.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  disable-swift-package-manager: false
  uses-material-design: true
