version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"

  - package-ecosystem: "pub"
    directory: "/multimedia_picker"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"
  - package-ecosystem: "pub"
    directory: "/multimedia_picker/example"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"
  - package-ecosystem: "pub"
    directory: "/multimedia_picker_platform_interface"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"
  - package-ecosystem: "pub"
    directory: "/multimedia_picker_android"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"
  - package-ecosystem: "pub"
    directory: "/multimedia_picker_ios"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"
  - package-ecosystem: "pub"
    directory: "/multimedia_picker_testing"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:30"
      timezone: "Europe/Vienna"
