version: 0.0.3
name: multimedia_picker_testing
description: A multimedia_picker testing suite.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker_testing
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis
publish_to: none

topics:
  - multimedia-picker-test
  - multimedia-picker-testing
  - multimedia-picker-tests
  - multi-media-picker-test
  - multimedia-picker-testing-suite

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  multimedia_picker:
    path: ../multimedia_picker
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface

dev_dependencies:
  dart_code_metrics_presets: ^2.21.0
  flutter_lints: ^5.0.0
