version: 0.0.6
name: multimedia_picker
description: A Flutter plugin for iOS that provides a unified interface for picking media (images/videos).
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis
publish_to: none

topics:
  - camera
  - media-picker
  - multimedia
  - multimedia-picker
  - recorder

environment:
  sdk: ^3.9.2
  flutter: ">=3.34.5"

resolution: workspace

flutter:
  plugin:
    platforms:
      # android: # TODO!
      #   default_package: multimedia_picker_android
      ios:
        default_package: multimedia_picker_ios

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker_ios:
    path: ../multimedia_picker_ios
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface
