version: 0.0.1
name: multimedia_picker
description: Flutter plugin for selecting images from the iOS media library, and taking new media with the camera.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis
publish_to: none

topics:
  - camera
  - media-picker
  - multimedia
  - multimedia-picker
  - recorder

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

resolution: workspace

flutter:
  plugin:
    platforms:
      # android: # TODO!
      #   default_package: multimedia_picker_android
      ios:
        default_package: multimedia_picker_ios

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker_ios:
    path: ../multimedia_picker_ios
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface

dev_dependencies:
  dart_code_metrics_presets: ^2.20.0
  flutter_lints: ^5.0.0
