// Copyright 2025 Roman Cinis. All rights reserved.
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v25.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    final Iterable<Object?> keys = (a as Map<Object?, Object?>).keys;
    return a.length == b.length &&
        keys.every(
          (Object? key) =>
              (b as Map<Object?, Object?>).containsKey(key) &&
              _deepEquals(a[key], b[key]),
        );
  }
  return a == b;
}

enum CaptureSessionPreset {
  cif352x288,
  vga640x480,
  hd1280x720,
  hd1920x1080,
  hd4K3840x2160,
  photo,
}

enum EditTool { draw, clip, imageSticker, textSticker, mosaic, filter, adjust }

enum UiLocale {
  system,
  chineseSimplified,
  chineseTraditional,
  english,
  japanese,
  french,
  german,
  russian,
  vietnamese,
  korean,
  malay,
  italian,
  indonesian,
  portuguese,
  spanish,
  turkish,
  arabic,
  dutch,
}

enum AdjustSliderType { vertical, horizontal }

enum AdjustTool { brightness, contrast, saturation }

enum CancelButtonStyle { text, image }

enum DevicePosition { back, front }

enum ExposureMode { autoExpose, continuousAutoExposure }

enum FocusMode { autoFocus, continuousAutoFocus }

enum HudStyle { light, lightBlur, dark, darkBlur }

enum ImpactFeedbackStyle { light, medium, heavy }

enum MediaType { image, video }

enum PhotoBrowserStyle { embedAlbumList, externalAlbumList }

enum VideoExportType { mov, mp4 }

enum VideoStabilization { off, standard, cinematic, cinematicExtended }

enum CameraOrientation {
  any,
  portrait,
  portraitUpsideDown,
  landscapeRight,
  landscapeLeft,
}

class RawOverlayImage {
  RawOverlayImage({
    required this.path,
    this.isAsset = false,
    this.opacity = 1,
    this.rotationAngle = 0,
    this.tintColor = 0x00000000,
  });

  String path;

  bool isAsset;

  double opacity;

  double rotationAngle;

  int tintColor;

  List<Object?> _toList() {
    return <Object?>[path, isAsset, opacity, rotationAngle, tintColor];
  }

  Object encode() {
    return _toList();
  }

  static RawOverlayImage decode(Object result) {
    result as List<Object?>;
    return RawOverlayImage(
      path: result[0]! as String,
      isAsset: result[1]! as bool,
      opacity: result[2]! as double,
      rotationAngle: result[3]! as double,
      tintColor: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawOverlayImage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return path == other.path &&
        isAsset == other.isAsset &&
        opacity == other.opacity &&
        rotationAngle == other.rotationAngle &&
        tintColor == other.tintColor;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RawLocalizations {
  RawLocalizations({this.iOsCameraTapToRecordVideoTip});

  String? iOsCameraTapToRecordVideoTip;

  List<Object?> _toList() {
    return <Object?>[iOsCameraTapToRecordVideoTip];
  }

  Object encode() {
    return _toList();
  }

  static RawLocalizations decode(Object result) {
    result as List<Object?>;
    return RawLocalizations(iOsCameraTapToRecordVideoTip: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawLocalizations || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return iOsCameraTapToRecordVideoTip == other.iOsCameraTapToRecordVideoTip;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RawUiConfiguration {
  RawUiConfiguration({
    this.sortAscending = true,
    this.style = PhotoBrowserStyle.embedAlbumList,
    this.isDarkStatusBarStyle,
    this.navCancelButtonStyle = CancelButtonStyle.image,
    this.showStatusBarInPreviewInterface = false,
    this.hudStyle = HudStyle.dark,
    this.adjustSliderType = AdjustSliderType.vertical,
    this.cellCornerRadio = 0,
    this.columnCount = 4,
    this.minimumItemSpacing = 2,
    this.minimumLineSpacing = 2,
    this.animateSelectButtonWhenSelectInThumbnail = false,
    this.animateSelectButtonWhenSelectInPreview = true,
    this.selectButtonAnimationDuration = 0.5,
    this.showIndexOnSelectButton = false,
    this.showScrollToBottomButton = false,
    this.showCaptureImageOnTakePhotoButton = false,
    this.showSelectedMask = true,
    this.showSelectedBorder = false,
    this.showInvalidMask = true,
    this.showSelectedPhotoPreview = true,
    this.showAddPhotoButton = true,
    this.showEnterSettingTips = true,
    this.shouldCenterTools = false,
    this.timeout = 20,
    this.languageType = UiLocale.system,
    this.themeFontName,
    this.themeColor = 0xFFf0aa00,
    this.l10n,
  });

  bool sortAscending;

  PhotoBrowserStyle style;

  bool? isDarkStatusBarStyle;

  CancelButtonStyle navCancelButtonStyle;

  bool showStatusBarInPreviewInterface;

  HudStyle hudStyle;

  AdjustSliderType adjustSliderType;

  double cellCornerRadio;

  int columnCount;

  double minimumItemSpacing;

  double minimumLineSpacing;

  bool animateSelectButtonWhenSelectInThumbnail;

  bool animateSelectButtonWhenSelectInPreview;

  double selectButtonAnimationDuration;

  bool showIndexOnSelectButton;

  bool showScrollToBottomButton;

  bool showCaptureImageOnTakePhotoButton;

  bool showSelectedMask;

  bool showSelectedBorder;

  bool showInvalidMask;

  bool showSelectedPhotoPreview;

  bool showAddPhotoButton;

  bool showEnterSettingTips;

  bool shouldCenterTools;

  double timeout;

  UiLocale languageType;

  String? themeFontName;

  int themeColor;

  RawLocalizations? l10n;

  List<Object?> _toList() {
    return <Object?>[
      sortAscending,
      style,
      isDarkStatusBarStyle,
      navCancelButtonStyle,
      showStatusBarInPreviewInterface,
      hudStyle,
      adjustSliderType,
      cellCornerRadio,
      columnCount,
      minimumItemSpacing,
      minimumLineSpacing,
      animateSelectButtonWhenSelectInThumbnail,
      animateSelectButtonWhenSelectInPreview,
      selectButtonAnimationDuration,
      showIndexOnSelectButton,
      showScrollToBottomButton,
      showCaptureImageOnTakePhotoButton,
      showSelectedMask,
      showSelectedBorder,
      showInvalidMask,
      showSelectedPhotoPreview,
      showAddPhotoButton,
      showEnterSettingTips,
      shouldCenterTools,
      timeout,
      languageType,
      themeFontName,
      themeColor,
      l10n,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RawUiConfiguration decode(Object result) {
    result as List<Object?>;
    return RawUiConfiguration(
      sortAscending: result[0]! as bool,
      style: result[1]! as PhotoBrowserStyle,
      isDarkStatusBarStyle: result[2] as bool?,
      navCancelButtonStyle: result[3]! as CancelButtonStyle,
      showStatusBarInPreviewInterface: result[4]! as bool,
      hudStyle: result[5]! as HudStyle,
      adjustSliderType: result[6]! as AdjustSliderType,
      cellCornerRadio: result[7]! as double,
      columnCount: result[8]! as int,
      minimumItemSpacing: result[9]! as double,
      minimumLineSpacing: result[10]! as double,
      animateSelectButtonWhenSelectInThumbnail: result[11]! as bool,
      animateSelectButtonWhenSelectInPreview: result[12]! as bool,
      selectButtonAnimationDuration: result[13]! as double,
      showIndexOnSelectButton: result[14]! as bool,
      showScrollToBottomButton: result[15]! as bool,
      showCaptureImageOnTakePhotoButton: result[16]! as bool,
      showSelectedMask: result[17]! as bool,
      showSelectedBorder: result[18]! as bool,
      showInvalidMask: result[19]! as bool,
      showSelectedPhotoPreview: result[20]! as bool,
      showAddPhotoButton: result[21]! as bool,
      showEnterSettingTips: result[22]! as bool,
      shouldCenterTools: result[23]! as bool,
      timeout: result[24]! as double,
      languageType: result[25]! as UiLocale,
      themeFontName: result[26] as String?,
      themeColor: result[27]! as int,
      l10n: result[28] as RawLocalizations?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawUiConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return sortAscending == other.sortAscending &&
        style == other.style &&
        isDarkStatusBarStyle == other.isDarkStatusBarStyle &&
        navCancelButtonStyle == other.navCancelButtonStyle &&
        showStatusBarInPreviewInterface ==
            other.showStatusBarInPreviewInterface &&
        hudStyle == other.hudStyle &&
        adjustSliderType == other.adjustSliderType &&
        cellCornerRadio == other.cellCornerRadio &&
        columnCount == other.columnCount &&
        minimumItemSpacing == other.minimumItemSpacing &&
        minimumLineSpacing == other.minimumLineSpacing &&
        animateSelectButtonWhenSelectInThumbnail ==
            other.animateSelectButtonWhenSelectInThumbnail &&
        animateSelectButtonWhenSelectInPreview ==
            other.animateSelectButtonWhenSelectInPreview &&
        selectButtonAnimationDuration == other.selectButtonAnimationDuration &&
        showIndexOnSelectButton == other.showIndexOnSelectButton &&
        showScrollToBottomButton == other.showScrollToBottomButton &&
        showCaptureImageOnTakePhotoButton ==
            other.showCaptureImageOnTakePhotoButton &&
        showSelectedMask == other.showSelectedMask &&
        showSelectedBorder == other.showSelectedBorder &&
        showInvalidMask == other.showInvalidMask &&
        showSelectedPhotoPreview == other.showSelectedPhotoPreview &&
        showAddPhotoButton == other.showAddPhotoButton &&
        showEnterSettingTips == other.showEnterSettingTips &&
        shouldCenterTools == other.shouldCenterTools &&
        timeout == other.timeout &&
        languageType == other.languageType &&
        themeFontName == other.themeFontName &&
        themeColor == other.themeColor &&
        l10n == other.l10n;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class ClipAspectRatio {
  ClipAspectRatio({required this.aspectRatioX, required this.aspectRatioY});

  int aspectRatioX;

  int aspectRatioY;

  List<Object?> _toList() {
    return <Object?>[aspectRatioX, aspectRatioY];
  }

  Object encode() {
    return _toList();
  }

  static ClipAspectRatio decode(Object result) {
    result as List<Object?>;
    return ClipAspectRatio(
      aspectRatioX: result[0]! as int,
      aspectRatioY: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ClipAspectRatio || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return aspectRatioX == other.aspectRatioX &&
        aspectRatioY == other.aspectRatioY;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class ClipOptions {
  ClipOptions({this.isCircle = false, this.aspectRatio});

  bool isCircle;

  ClipAspectRatio? aspectRatio;

  List<Object?> _toList() {
    return <Object?>[isCircle, aspectRatio];
  }

  Object encode() {
    return _toList();
  }

  static ClipOptions decode(Object result) {
    result as List<Object?>;
    return ClipOptions(
      isCircle: result[0]! as bool,
      aspectRatio: result[1] as ClipAspectRatio?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ClipOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return isCircle == other.isCircle && aspectRatio == other.aspectRatio;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RawMediaData {
  RawMediaData({
    required this.path,
    this.thumbPath,
    required this.type,
    this.durationSec,
  });

  String path;

  String? thumbPath;

  MediaType type;

  int? durationSec;

  List<Object?> _toList() {
    return <Object?>[path, thumbPath, type, durationSec];
  }

  Object encode() {
    return _toList();
  }

  static RawMediaData decode(Object result) {
    result as List<Object?>;
    return RawMediaData(
      path: result[0]! as String,
      thumbPath: result[1] as String?,
      type: result[2]! as MediaType,
      durationSec: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawMediaData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return path == other.path &&
        thumbPath == other.thumbPath &&
        type == other.type &&
        durationSec == other.durationSec;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RawPickerConfiguration {
  RawPickerConfiguration({
    this.maxSelectCount = 9,
    this.maxVideoSelectCount = 0,
    this.minVideoSelectCount = 0,
    this.allowMixSelect = true,
    this.maxPreviewCount = 20,
    this.initialIndex = 1,
    this.allowSelectImage = true,
    this.allowSelectVideo = true,
    this.downloadVideoBeforeSelecting = false,
    this.allowSelectGif = true,
    this.allowSelectLivePhoto = false,
    this.allowTakePhotoInLibrary = true,
    this.callbackDirectlyAfterTakingPhoto = false,
    this.allowEditImage = true,
    this.allowEditVideo = true,
    this.editAfterSelectThumbnailImage = false,
    this.cropVideoAfterSelectThumbnail = true,
    this.saveNewImageAfterEdit = true,
    this.allowSlideSelect = true,
    this.autoScrollWhenSlideSelectIsActive = true,
    this.autoScrollMaxSpeed = 600,
    this.allowDragSelect = false,
    this.allowSelectOriginal = true,
    this.alwaysRequestOriginal = false,
    this.showOriginalSizeWhenSelectOriginal = true,
    this.allowPreviewPhotos = true,
    this.showPreviewButtonInAlbum = true,
    this.showSelectCountOnDoneButton = true,
    this.showSelectButtonWhenSingleSelect = false,
    this.showSelectedIndex = true,
    this.thumbnailPrefix = '.thumbnail_',
    this.thumbnailWidth = 200,
    this.maxEditVideoDurationSeconds = 30,
    this.maxSelectVideoDurationSeconds = 120,
    this.minSelectVideoDurationSeconds = 0,
    this.maxSelectVideoDataSizeKB,
    this.minSelectVideoDataSizeKB = 0,
    this.useCustomCamera = true,
    this.directoryPath,
    this.filename,
  });

  int maxSelectCount;

  int maxVideoSelectCount;

  int minVideoSelectCount;

  bool allowMixSelect;

  int maxPreviewCount;

  int initialIndex;

  bool allowSelectImage;

  bool allowSelectVideo;

  bool downloadVideoBeforeSelecting;

  bool allowSelectGif;

  bool allowSelectLivePhoto;

  bool allowTakePhotoInLibrary;

  bool callbackDirectlyAfterTakingPhoto;

  bool allowEditImage;

  bool allowEditVideo;

  bool editAfterSelectThumbnailImage;

  bool cropVideoAfterSelectThumbnail;

  bool saveNewImageAfterEdit;

  bool allowSlideSelect;

  bool autoScrollWhenSlideSelectIsActive;

  double autoScrollMaxSpeed;

  bool allowDragSelect;

  bool allowSelectOriginal;

  bool alwaysRequestOriginal;

  bool showOriginalSizeWhenSelectOriginal;

  bool allowPreviewPhotos;

  bool showPreviewButtonInAlbum;

  bool showSelectCountOnDoneButton;

  bool showSelectButtonWhenSingleSelect;

  bool showSelectedIndex;

  String thumbnailPrefix;

  int thumbnailWidth;

  int maxEditVideoDurationSeconds;

  int maxSelectVideoDurationSeconds;

  int minSelectVideoDurationSeconds;

  double? maxSelectVideoDataSizeKB;

  double minSelectVideoDataSizeKB;

  bool useCustomCamera;

  String? directoryPath;

  String? filename;

  List<Object?> _toList() {
    return <Object?>[
      maxSelectCount,
      maxVideoSelectCount,
      minVideoSelectCount,
      allowMixSelect,
      maxPreviewCount,
      initialIndex,
      allowSelectImage,
      allowSelectVideo,
      downloadVideoBeforeSelecting,
      allowSelectGif,
      allowSelectLivePhoto,
      allowTakePhotoInLibrary,
      callbackDirectlyAfterTakingPhoto,
      allowEditImage,
      allowEditVideo,
      editAfterSelectThumbnailImage,
      cropVideoAfterSelectThumbnail,
      saveNewImageAfterEdit,
      allowSlideSelect,
      autoScrollWhenSlideSelectIsActive,
      autoScrollMaxSpeed,
      allowDragSelect,
      allowSelectOriginal,
      alwaysRequestOriginal,
      showOriginalSizeWhenSelectOriginal,
      allowPreviewPhotos,
      showPreviewButtonInAlbum,
      showSelectCountOnDoneButton,
      showSelectButtonWhenSingleSelect,
      showSelectedIndex,
      thumbnailPrefix,
      thumbnailWidth,
      maxEditVideoDurationSeconds,
      maxSelectVideoDurationSeconds,
      minSelectVideoDurationSeconds,
      maxSelectVideoDataSizeKB,
      minSelectVideoDataSizeKB,
      useCustomCamera,
      directoryPath,
      filename,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RawPickerConfiguration decode(Object result) {
    result as List<Object?>;
    return RawPickerConfiguration(
      maxSelectCount: result[0]! as int,
      maxVideoSelectCount: result[1]! as int,
      minVideoSelectCount: result[2]! as int,
      allowMixSelect: result[3]! as bool,
      maxPreviewCount: result[4]! as int,
      initialIndex: result[5]! as int,
      allowSelectImage: result[6]! as bool,
      allowSelectVideo: result[7]! as bool,
      downloadVideoBeforeSelecting: result[8]! as bool,
      allowSelectGif: result[9]! as bool,
      allowSelectLivePhoto: result[10]! as bool,
      allowTakePhotoInLibrary: result[11]! as bool,
      callbackDirectlyAfterTakingPhoto: result[12]! as bool,
      allowEditImage: result[13]! as bool,
      allowEditVideo: result[14]! as bool,
      editAfterSelectThumbnailImage: result[15]! as bool,
      cropVideoAfterSelectThumbnail: result[16]! as bool,
      saveNewImageAfterEdit: result[17]! as bool,
      allowSlideSelect: result[18]! as bool,
      autoScrollWhenSlideSelectIsActive: result[19]! as bool,
      autoScrollMaxSpeed: result[20]! as double,
      allowDragSelect: result[21]! as bool,
      allowSelectOriginal: result[22]! as bool,
      alwaysRequestOriginal: result[23]! as bool,
      showOriginalSizeWhenSelectOriginal: result[24]! as bool,
      allowPreviewPhotos: result[25]! as bool,
      showPreviewButtonInAlbum: result[26]! as bool,
      showSelectCountOnDoneButton: result[27]! as bool,
      showSelectButtonWhenSingleSelect: result[28]! as bool,
      showSelectedIndex: result[29]! as bool,
      thumbnailPrefix: result[30]! as String,
      thumbnailWidth: result[31]! as int,
      maxEditVideoDurationSeconds: result[32]! as int,
      maxSelectVideoDurationSeconds: result[33]! as int,
      minSelectVideoDurationSeconds: result[34]! as int,
      maxSelectVideoDataSizeKB: result[35] as double?,
      minSelectVideoDataSizeKB: result[36]! as double,
      useCustomCamera: result[37]! as bool,
      directoryPath: result[38] as String?,
      filename: result[39] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawPickerConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return maxSelectCount == other.maxSelectCount &&
        maxVideoSelectCount == other.maxVideoSelectCount &&
        minVideoSelectCount == other.minVideoSelectCount &&
        allowMixSelect == other.allowMixSelect &&
        maxPreviewCount == other.maxPreviewCount &&
        initialIndex == other.initialIndex &&
        allowSelectImage == other.allowSelectImage &&
        allowSelectVideo == other.allowSelectVideo &&
        downloadVideoBeforeSelecting == other.downloadVideoBeforeSelecting &&
        allowSelectGif == other.allowSelectGif &&
        allowSelectLivePhoto == other.allowSelectLivePhoto &&
        allowTakePhotoInLibrary == other.allowTakePhotoInLibrary &&
        callbackDirectlyAfterTakingPhoto ==
            other.callbackDirectlyAfterTakingPhoto &&
        allowEditImage == other.allowEditImage &&
        allowEditVideo == other.allowEditVideo &&
        editAfterSelectThumbnailImage == other.editAfterSelectThumbnailImage &&
        cropVideoAfterSelectThumbnail == other.cropVideoAfterSelectThumbnail &&
        saveNewImageAfterEdit == other.saveNewImageAfterEdit &&
        allowSlideSelect == other.allowSlideSelect &&
        autoScrollWhenSlideSelectIsActive ==
            other.autoScrollWhenSlideSelectIsActive &&
        autoScrollMaxSpeed == other.autoScrollMaxSpeed &&
        allowDragSelect == other.allowDragSelect &&
        allowSelectOriginal == other.allowSelectOriginal &&
        alwaysRequestOriginal == other.alwaysRequestOriginal &&
        showOriginalSizeWhenSelectOriginal ==
            other.showOriginalSizeWhenSelectOriginal &&
        allowPreviewPhotos == other.allowPreviewPhotos &&
        showPreviewButtonInAlbum == other.showPreviewButtonInAlbum &&
        showSelectCountOnDoneButton == other.showSelectCountOnDoneButton &&
        showSelectButtonWhenSingleSelect ==
            other.showSelectButtonWhenSingleSelect &&
        showSelectedIndex == other.showSelectedIndex &&
        thumbnailPrefix == other.thumbnailPrefix &&
        thumbnailWidth == other.thumbnailWidth &&
        maxEditVideoDurationSeconds == other.maxEditVideoDurationSeconds &&
        maxSelectVideoDurationSeconds == other.maxSelectVideoDurationSeconds &&
        minSelectVideoDurationSeconds == other.minSelectVideoDurationSeconds &&
        maxSelectVideoDataSizeKB == other.maxSelectVideoDataSizeKB &&
        minSelectVideoDataSizeKB == other.minSelectVideoDataSizeKB &&
        useCustomCamera == other.useCustomCamera &&
        directoryPath == other.directoryPath &&
        filename == other.filename;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RawEditConfiguration {
  RawEditConfiguration({
    this.tools = const [],
    this.clipOptions,
    this.adjustTools = const [],
    this.showClipDirectlyIfOnlyHasClipTool = false,
    this.impactFeedbackWhenAdjustSliderValueIsZero = true,
    this.impactFeedbackStyle = ImpactFeedbackStyle.medium,
    this.dimClippedAreaDuringAdjustments = false,
    this.minimumZoomScale = 1,
  });

  List<EditTool> tools;

  ClipOptions? clipOptions;

  List<AdjustTool> adjustTools;

  bool showClipDirectlyIfOnlyHasClipTool;

  bool impactFeedbackWhenAdjustSliderValueIsZero;

  ImpactFeedbackStyle impactFeedbackStyle;

  bool dimClippedAreaDuringAdjustments;

  double minimumZoomScale;

  List<Object?> _toList() {
    return <Object?>[
      tools,
      clipOptions,
      adjustTools,
      showClipDirectlyIfOnlyHasClipTool,
      impactFeedbackWhenAdjustSliderValueIsZero,
      impactFeedbackStyle,
      dimClippedAreaDuringAdjustments,
      minimumZoomScale,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RawEditConfiguration decode(Object result) {
    result as List<Object?>;
    return RawEditConfiguration(
      tools: (result[0] as List<Object?>?)!.cast<EditTool>(),
      clipOptions: result[1] as ClipOptions?,
      adjustTools: (result[2] as List<Object?>?)!.cast<AdjustTool>(),
      showClipDirectlyIfOnlyHasClipTool: result[3]! as bool,
      impactFeedbackWhenAdjustSliderValueIsZero: result[4]! as bool,
      impactFeedbackStyle: result[5]! as ImpactFeedbackStyle,
      dimClippedAreaDuringAdjustments: result[6]! as bool,
      minimumZoomScale: result[7]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawEditConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(tools, other.tools) &&
        clipOptions == other.clipOptions &&
        _deepEquals(adjustTools, other.adjustTools) &&
        showClipDirectlyIfOnlyHasClipTool ==
            other.showClipDirectlyIfOnlyHasClipTool &&
        impactFeedbackWhenAdjustSliderValueIsZero ==
            other.impactFeedbackWhenAdjustSliderValueIsZero &&
        impactFeedbackStyle == other.impactFeedbackStyle &&
        dimClippedAreaDuringAdjustments ==
            other.dimClippedAreaDuringAdjustments &&
        minimumZoomScale == other.minimumZoomScale;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RawCameraConfiguration {
  RawCameraConfiguration({
    this.allowTakePhoto = true,
    this.allowRecordVideo = true,
    this.captureTimerSeconds = 0,
    this.minDurationSeconds = 0,
    this.maxDurationSeconds = 30,
    this.isFrontVideoMirrored = true,
    this.sessionPreset = CaptureSessionPreset.hd1920x1080,
    this.focusMode = FocusMode.continuousAutoFocus,
    this.exposureMode = ExposureMode.continuousAutoExposure,
    this.showFlashSwitch = true,
    this.allowSwitchCamera = true,
    this.tapToRecordVideo = true,
    this.enableWideCameras = true,
    this.videoExportType = VideoExportType.mp4,
    this.devicePosition = DevicePosition.back,
    this.playCameraSound = true,
    this.overlayImage,
    this.videoStabilization,
    this.orientation = CameraOrientation.any,
  });

  bool allowTakePhoto;

  bool allowRecordVideo;

  int captureTimerSeconds;

  int minDurationSeconds;

  int maxDurationSeconds;

  bool isFrontVideoMirrored;

  CaptureSessionPreset sessionPreset;

  FocusMode focusMode;

  ExposureMode exposureMode;

  bool showFlashSwitch;

  bool allowSwitchCamera;

  bool tapToRecordVideo;

  bool enableWideCameras;

  VideoExportType videoExportType;

  DevicePosition devicePosition;

  bool playCameraSound;

  RawOverlayImage? overlayImage;

  VideoStabilization? videoStabilization;

  CameraOrientation orientation;

  List<Object?> _toList() {
    return <Object?>[
      allowTakePhoto,
      allowRecordVideo,
      captureTimerSeconds,
      minDurationSeconds,
      maxDurationSeconds,
      isFrontVideoMirrored,
      sessionPreset,
      focusMode,
      exposureMode,
      showFlashSwitch,
      allowSwitchCamera,
      tapToRecordVideo,
      enableWideCameras,
      videoExportType,
      devicePosition,
      playCameraSound,
      overlayImage,
      videoStabilization,
      orientation,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RawCameraConfiguration decode(Object result) {
    result as List<Object?>;
    return RawCameraConfiguration(
      allowTakePhoto: result[0]! as bool,
      allowRecordVideo: result[1]! as bool,
      captureTimerSeconds: result[2]! as int,
      minDurationSeconds: result[3]! as int,
      maxDurationSeconds: result[4]! as int,
      isFrontVideoMirrored: result[5]! as bool,
      sessionPreset: result[6]! as CaptureSessionPreset,
      focusMode: result[7]! as FocusMode,
      exposureMode: result[8]! as ExposureMode,
      showFlashSwitch: result[9]! as bool,
      allowSwitchCamera: result[10]! as bool,
      tapToRecordVideo: result[11]! as bool,
      enableWideCameras: result[12]! as bool,
      videoExportType: result[13]! as VideoExportType,
      devicePosition: result[14]! as DevicePosition,
      playCameraSound: result[15]! as bool,
      overlayImage: result[16] as RawOverlayImage?,
      videoStabilization: result[17] as VideoStabilization?,
      orientation: result[18]! as CameraOrientation,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawCameraConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return allowTakePhoto == other.allowTakePhoto &&
        allowRecordVideo == other.allowRecordVideo &&
        captureTimerSeconds == other.captureTimerSeconds &&
        minDurationSeconds == other.minDurationSeconds &&
        maxDurationSeconds == other.maxDurationSeconds &&
        isFrontVideoMirrored == other.isFrontVideoMirrored &&
        sessionPreset == other.sessionPreset &&
        focusMode == other.focusMode &&
        exposureMode == other.exposureMode &&
        showFlashSwitch == other.showFlashSwitch &&
        allowSwitchCamera == other.allowSwitchCamera &&
        tapToRecordVideo == other.tapToRecordVideo &&
        enableWideCameras == other.enableWideCameras &&
        videoExportType == other.videoExportType &&
        devicePosition == other.devicePosition &&
        playCameraSound == other.playCameraSound &&
        overlayImage == other.overlayImage &&
        videoStabilization == other.videoStabilization &&
        orientation == other.orientation;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CaptureSessionPreset) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is EditTool) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is UiLocale) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is AdjustSliderType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is AdjustTool) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is CancelButtonStyle) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is DevicePosition) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is ExposureMode) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is FocusMode) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is HudStyle) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is ImpactFeedbackStyle) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is MediaType) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    } else if (value is PhotoBrowserStyle) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    } else if (value is VideoExportType) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    } else if (value is VideoStabilization) {
      buffer.putUint8(143);
      writeValue(buffer, value.index);
    } else if (value is CameraOrientation) {
      buffer.putUint8(144);
      writeValue(buffer, value.index);
    } else if (value is RawOverlayImage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is RawLocalizations) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is RawUiConfiguration) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is ClipAspectRatio) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is ClipOptions) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is RawMediaData) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is RawPickerConfiguration) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is RawEditConfiguration) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is RawCameraConfiguration) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureSessionPreset.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : EditTool.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : UiLocale.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : AdjustSliderType.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : AdjustTool.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CancelButtonStyle.values[value];
      case 135:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DevicePosition.values[value];
      case 136:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ExposureMode.values[value];
      case 137:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FocusMode.values[value];
      case 138:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : HudStyle.values[value];
      case 139:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ImpactFeedbackStyle.values[value];
      case 140:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MediaType.values[value];
      case 141:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PhotoBrowserStyle.values[value];
      case 142:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VideoExportType.values[value];
      case 143:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VideoStabilization.values[value];
      case 144:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraOrientation.values[value];
      case 145:
        return RawOverlayImage.decode(readValue(buffer)!);
      case 146:
        return RawLocalizations.decode(readValue(buffer)!);
      case 147:
        return RawUiConfiguration.decode(readValue(buffer)!);
      case 148:
        return ClipAspectRatio.decode(readValue(buffer)!);
      case 149:
        return ClipOptions.decode(readValue(buffer)!);
      case 150:
        return RawMediaData.decode(readValue(buffer)!);
      case 151:
        return RawPickerConfiguration.decode(readValue(buffer)!);
      case 152:
        return RawEditConfiguration.decode(readValue(buffer)!);
      case 153:
        return RawCameraConfiguration.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MultiMediaApi {
  /// Constructor for [MultiMediaApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MultiMediaApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix =
           messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<RawMediaData?> openCamera(
    RawCameraConfiguration cameraConfig,
    RawEditConfiguration editConfig,
    RawPickerConfiguration pickerConfig,
    RawUiConfiguration uiConfig,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.multimedia_picker.MultiMediaApi.openCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[cameraConfig, editConfig, pickerConfig, uiConfig],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RawMediaData?);
    }
  }

  Future<RawMediaData?> editMedia(
    RawMediaData data,
    RawEditConfiguration editConfig,
    RawPickerConfiguration pickerConfig,
    RawUiConfiguration uiConfig,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.multimedia_picker.MultiMediaApi.editMedia$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[data, editConfig, pickerConfig, uiConfig],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RawMediaData?);
    }
  }

  Future<List<RawMediaData>?> openGallery(
    RawEditConfiguration editConfig,
    RawPickerConfiguration pickerConfig,
    RawUiConfiguration uiConfig,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.multimedia_picker.MultiMediaApi.openGallery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[editConfig, pickerConfig, uiConfig],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)?.cast<RawMediaData>();
    }
  }
}
