version: 0.0.3
name: multimedia_picker_platform_interface
description: A common platform interface for the multimedia_picker plugin.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker_platform_interface
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  dart_code_metrics_presets: ^2.22.0
  flutter_lints: ^5.0.0
  pigeon: ^25.3.1
