name: multimedia_picker_platform_interface
description: A common platform interface for the multimedia_picker plugin
version: 0.0.1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  dart_code_metrics_presets: ^2.20.0
  flutter_lints: ^5.0.0
  pigeon: ^24.1.1
