version: 0.0.5
name: multimedia_picker_platform_interface
description: A common platform interface for the multimedia_picker plugin.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker_platform_interface
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  pigeon: ^26.0.1
