version: 0.0.6
name: multimedia_picker_example
description: Demonstrates how to use the multimedia_picker plugin.
publish_to: none

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker:
    path: ../
  path: ^1.9.1
  path_provider: ^2.1.5
  world_countries: ^3.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/
