version: 0.0.6
name: multimedia_picker_android
description: Android implementation of the multimedia_picker plugin.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker_android
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.4"

resolution: workspace

flutter:
  plugin:
    implements: multimedia_picker
    platforms:
      android:
        package: is.tsin.multimedia.picker
        pluginClass: MultimediaPickerPlugin
        dartPluginClass: MultimediaPickerAndroid

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface
