name: multimedia_picker_ios
description: iOS implementation of the multimedia_picker plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

flutter:
  plugin:
    implements: multimedia_picker
    platforms:
      ios:
        pluginClass: MultimediaPickerPlugin
        dartPluginClass: MultimediaPickerIOS

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface

dev_dependencies:
  dart_code_metrics_presets: ^2.20.0
  flutter_lints: ^5.0.0
