version: 0.0.6
name: multimedia_picker_ios
description: iOS implementation of the multimedia_picker plugin.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker_ios
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.25.4"

resolution: workspace

flutter:
  plugin:
    implements: multimedia_picker
    platforms:
      ios:
        pluginClass: MultimediaPickerPlugin
        dartPluginClass: MultimediaPickerIOS

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface
