version: 0.0.3
name: multimedia_picker_ios
description: iOS implementation of the multimedia_picker plugin.
repository: https://github.com/tsinis/multi_media_picker/tree/main/multimedia_picker_ios
issue_tracker: https://github.com/tsinis/multi_media_picker/issues
maintainer: Roman Cinis
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

resolution: workspace

flutter:
  plugin:
    implements: multimedia_picker
    platforms:
      ios:
        pluginClass: MultimediaPickerPlugin
        dartPluginClass: MultimediaPickerIOS

dependencies:
  flutter:
    sdk: flutter
  multimedia_picker_platform_interface:
    path: ../multimedia_picker_platform_interface

dev_dependencies:
  dart_code_metrics_presets: ^2.21.0
  flutter_lints: ^5.0.0
